# Colors (Tomorrow Night)
colors:
  # Default colors
  primary:
    background: '#1d1f21'
    #foreground: '#c5c8c6'
    foreground: '#1d1f21'


    # Bright and dim foreground colors
    #
    # The dimmed foreground color is calculated automatically if it is not
    # present. If the bright foreground color is not set, or
    # `draw_bold_text_with_bright_colors` is `false`, the normal foreground
    # color will be used.
    dim_foreground: '#828482'
    bright_foreground: '#eaeaea'

# Background opacity
#
# Window opacity as a floating point number from `0.0` to `1.0`.
# The value `0.0` is completely transparent and `1.0` is opaque.
background_opacity: 1.0